=== LaTortueQuiParl/L3Info/Modelisation/Projet/BookDTD.dtd
<!ELEMENT Catalogue (Livre+)>
<!ELEMENT Livre (Auteur+,Titre,Genre,Prix,Quantite,DateSortie,Description?,Commentaires*)>
<!ATTLIST Livre id ID #REQUIRED>
<!ATTLIST Livre nbPage CDATA #REQUIRED>
<!ATTLIST Livre image CDATA #IMPLIED>
<!ATTLIST Livre lang (fr | en) #REQUIRED>
<!ELEMENT Auteur (#PCDATA)>
<!ELEMENT Titre (#PCDATA)>
<!ELEMENT Genre (#PCDATA)>
<!ELEMENT Prix (#PCDATA)>
<!ELEMENT Quantite (#PCDATA)>
<!ELEMENT DateSortie (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT Commentaires (#PCDATA)>

=== LaTortueQuiParl/L3Info/Modelisation/Projet/Book.xml
<?XML version="1.0" encodage="UTF-8"?>
<!DOCTYPE repertoire SYSTEM "BookDTD.dtd">
<Catalogue>
    <Livre id="bk101" nbPage="325" image="Livre1.png" lang="fr">
       <Auteur>Garghentini, Davide</Auteur>
       <Titre>XML Developer's Guide</Titre>
       <Genre>Computer</Genre>
       <Prix>44.95</Prix>
       <Quantite>8</Quantite>
       <DateSortie>2000-10-01</DateSortie>
       <Description>An in-depth look at creating applications
       with XML.</Description>
       <!-- Je ne sais pas si on doit mettre une balise <Commentaires> ou bien si c'est autre chose (il pourrait y en avoir plusieurs)-->
       <Commentaires>Ce livre n'est pas mal !</Commentaires>
    </Livre>
    <Livre id="bk102" nbPage="85" image="Livre2.png" lang="en">
       <Auteur>Garcia, Debra</Auteur>
       <Titre>Midnight Rain</Titre>
       <Genre>Fantasy</Genre>
       <Prix>5.95</Prix>
       <Quantite>5</Quantite>
       <DateSortie>2000-12-16</DateSortie>
       <Description>A former architect battles corporate zombies,
       an evil sorceress, and her own childhood to become queen
       of the world.</Description>
       <!-- Pareil ici...-->
       <Commentaires>Ce livre est horrible ! je veux me crever les yeux !</Commentaires>
       <Commentaires>Je recommande.</Commentaires>
    </Livre>
 </Catalogue>
