=== LaTortueQuiParl/L3Info/Modelisation/Projet/ClientDTD.dtd
<!ELEMENT Clients (Client*)>
<!ELEMENT Client (Nom,Prenom,Naissance,Telephone,MotDePasse,Adresse,Mail,Historique?)>
<!ATTLIST Client id ID #REQUIRED>
<!ELEMENT Nom (#PCDATA)>
<!ELEMENT Prenom (#PCDATA)>
<!ELEMENT Naissance (#PCDATA)>
<!ELEMENT Telephone (#PCDATA)>
<!ELEMENT MotDePasse (#PCDATA)>
<!ELEMENT Adresse (Numero?,NomRue,CodePostal,Ville)>
<!ELEMENT Numero (#PCDATA)>
<!ELEMENT NomRue (#PCDATA)>
<!ELEMENT CodePostal (#PCDATA)>
<!ELEMENT Ville (#PCDATA)>
<!ELEMENT Mail (#PCDATA)>
<!ELEMENT Historique (Livre*)>
<!ELEMENT Livre EMPTY>
<!ATTLIST Livre id ID #REQUIRED>

=== LaTortueQuiParl/L3Info/Modelisation/Projet/Client.xml
<?XML version="1.0" encodage="UTF-8"?>
<!DOCTYPE repertoire SYSTEM "ClientDTD.dtd">
<Clients>
    <Client id="0854125">
        <Nom>Bouchard</Nom>
        <Prenom>Théo</Prenom>
        <Naissance>05/02/1965</Naissance>
        <Telephone>XXXXXXXXXX</Telephone>
        <MotDePasse>Michel Forever Tonight !</MotDePasse>
        <Adresse>
            <Numero>25</Numero>
            <NomRue>Rue de la 57ème Licorne</NomRue>
            <CodePostal>78564</CodePostal>
            <Ville>Pays du Nuage</Ville>
        </Adresse>
        <Mail>mail@mail.com</Mail>
        <Historique>
            <!-- L'id fait référence aux livres dans Book.xml-->
            <Livre id ="bk101"/>
        </Historique>
    </Client>
    <Client id="0854126">
        <Name>Doe</Name>
        <Prenom>Jhon</Prenom>
        <Naissance>Unknow</Naissance>
        <Telephone>Anonym</Telephone>
        <MotDePasse>I am hidding !</MotDePasse>
        <Adresse>
            <NomRue>He'll found you !</NomRue>
            <CodePostal>25007</CodePostal>
            <Ville>NoWhere</Ville>
        </Adresse>
        <Mail>secretAgent@Iamasecretagent.com</Mail>
        <Historique>
            <Livre id ="bk101"/>
            <Livre id ="bk102"/>
        </Historique>
    </Client>
</Clients>
